//
//  LogInRouter.swift
//  HelpMe
//
//  Created by mohamed hashem on 2/13/20.
//  Copyright (c) 2020 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogInRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginRouterInput {
}

class LogInRouter: LoginRouterInput {
  weak var viewController: LogInViewController!

    func navigateToHome() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let MainViewController = storyboard.instantiateViewController(identifier: "first")
        MainViewController.modalPresentationStyle = .fullScreen
        viewController.navigationController?.pushViewController(MainViewController, animated: true)
    }
}
