//
//  LogInModels.swift
//  HelpMe
//
//  Created by mohamed hashem on 2/13/20.
//  Copyright (c) 2020 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LogIn {
    enum Error: String, Swift.Error {
        case InvalidPassword
        case InvalidEmail
        case authenticationError
    }

}
