//
//  SignUpInteractor.swift
//  HelpMe
//
//  Created by mohamed hashem on 2/13/20.
//  Copyright (c) 2020 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol SignUpViewModelProtocol {
    func registerComplete()
    func registerFail(error: Error)
    func dataSavedError(error: Error)
}

class SignUpViewModel {
    var delegate: SignUpViewModelProtocol?
//    let currentUser = try MainModel.User.current.value()

    func regester(email: String, password: String) {
        Auth.auth().createUser(withEmail: email, password: password) { (result, error) in
            if let error = error {
                self.delegate?.registerFail(error: error)
            } else {
                let firebaseRealDataBase = Database.database().reference()
                let authPath = "UserNumber \(Int.random(in: 0...10000))"
                UserDefaults.standard.set(authPath, forKey: "userID")
                UserDefaults.standard.synchronize()
                let dataToFirebaseDatabase = self.setUserJson(email: email, password: password)
                firebaseRealDataBase.child("users/data/\(authPath)").setValue(dataToFirebaseDatabase) { (error, reference) in
                    if let error = error {
                        self.delegate?.dataSavedError(error: error)
                    } else {
                        self.delegate?.registerComplete()
                    }
                }
            }
        }
    }

    private func setUserJson(email: String, password: String) -> [String : Any] {
        let currentUser = try? MainModel.User.current.value()
        let dataToFirebaseDatabase: [String: Any] = ["email": email,
                                                     "password": password,
                                                     "name": currentUser?.userName as Any,
                                                     "phone":currentUser?.phone as Any,
                                                     "birthDate": currentUser?.birthdate?.description as Any,
                                                     "latitude": currentUser?.currentLocation?.latitude as Any,
                                                     "longitude": currentUser?.currentLocation?.longitude as Any
        ]
        return dataToFirebaseDatabase
    }
}
